### ISSUE TITLE
Linking fails

### ISSUE THREAD

**Issue by thk686** [miraisolutions/rTRNG#8]
I get

```
clang++ -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o epigrad.so RcppExports.o cellular.o epigrad.o /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rTRNG/libs/rTRNG.so -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-epigrad/00new/epigrad/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘epigrad’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-epigrad/00new/epigrad/libs/epigrad.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-epigrad/00new/epigrad/libs/epigrad.so, 6): Library not loaded: rTRNG.so
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-epigrad/00new/epigrad/libs/epigrad.so
  Reason: image not found
Error: loading failed
```
and

```
> rTRNG::LdFlags()
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rTRNG/libs/rTRNG.so
```
Should that not return -L and -l flags?

Makevars
```
PKG_LIBS += $(shell ${R_HOME}/bin/Rscript -e "RcppParallel::RcppParallelLibs()")
PKG_LIBS += $(shell ${R_HOME}/bin/Rscript -e "rTRNG::LdFlags()")
PKG_CPPFLAGS = -I"../inst/include" -I"../include"
CXX_STD = CXX17
```
NAMESPACE
```
importFrom(rTRNG,TRNG.Version)
```
DESCRIPTION
```
LinkingTo: 
    Rcpp,
    kdtools,
    rTRNG,
    RcppParallel
```

**Comment by riccardoporreca** [comment]
`rTRNG::LdFlags()` returns the direct path and should work just fine. See the comment in the source code for more context about this vs. `-l` and `-L`

https://github.com/miraisolutions/rTRNG/blob/8fac3fd96385146e43ded04b36cb123c443aebd7/R/LdFlags.R#L25-L31

Btw, I see many special flags in your `clang++`, not sure if any of those might interfere. Can you please try to run the script [inst/demos/rTRNGinPkg.R](https://github.com/miraisolutions/rTRNG/blob/8fac3fd96385146e43ded04b36cb123c443aebd7/inst/demos/rTRNGinPkg.R) (from the source package top directory of a local checkout of rTRNG)? If this works, you can try using this as a starting point for your package, otherwise there is maybe something in your setup (e.g. compiler flags) that might be causing problems.

**Comment by thk686** [comment]
Thanks for all your help. I realized what I really want is a stand-alone header-only rng so I just dropped the headers for pcg into my source. They support multiple streams. Problem solved.
